[package]
authors = ["Bruno Tavares <connect+github@bltavares.com>"]
name = "stitches"
version = "0.1.0"

[dependencies]
hyper = "0.7.2"
lazy_static = "0.1.15"
multipart = "0.4.1"
mustache = "0.6.3"
uuid = "0.1.18"
